version: '3.7'

networks:
  site1:
    driver: bridge
  site2:
    driver: bridge

services:                           ##php-fpm services

  proxy:
    image: meu-proxy:latest
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile-nginx
    container_name: proxy
    networks:
      - site1
    volumes:
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/proxy.conf:/opt/bitnami/nginx/conf/server_blocks/proxy.conf
    ports:
      - 80:8080
    depends_on:
      - site1
      - phpfpm

  site1:                           ##nginx services
    image: bitnami/nginx:latest
    container_name: site1
    networks:
      - site1
    depends_on:
      - phpfpm
    volumes:
      - ./app:/app
      - ./docker/nginx/site1.conf:/opt/bitnami/nginx/conf/server_blocks/site.conf
    working_dir: /app

  phpfpm:
    image: bitnami/php-fpm:latest
    user: 1000:1000
    container_name: phpfpm
    networks:
      - site1
    volumes: 
      - ./app:/app
      - ./docker/php-fpm/log:/var/log/phplog
      - ./docker/php-fpm/custom-php.ini:/opt/bitnami/php/etc/conf.d/custom-php.ini
      - ./docker/php-fpm/custom-phpfpm-1.conf:/opt/bitnami/php/etc/php-fpm.d/phpfpm.conf
    working_dir: /app

  phpfpm2:
    image: bitnami/php-fpm:latest
    user: 1000:1000
    container_name: phpfpm2
    networks:
      - site1
    volumes: 
      - ./app:/app
      - ./docker/php-fpm/log:/var/log/phplog
      - ./docker/php-fpm/custom-php.ini:/opt/bitnami/php/etc/conf.d/custom-php.ini
      - ./docker/php-fpm/custom-phpfpm-2.conf:/opt/bitnami/php/etc/php-fpm.d/phpfpm.conf
    working_dir: /app

  phpfpm3:
    image: bitnami/php-fpm:latest
    user: 1000:1000
    container_name: phpfpm3
    networks:
      - site1
    volumes: 
      - ./app:/app
      - ./docker/php-fpm/log:/var/log/phplog
      - ./docker/php-fpm/custom-php.ini:/opt/bitnami/php/etc/conf.d/custom-php.ini
      - ./docker/php-fpm/custom-phpfpm-3.conf:/opt/bitnami/php/etc/php-fpm.d/phpfpm.conf
    working_dir: /app

  # php4_site2:
  #   image: bitnami/php-fpm:latest
  #   container_name: php4_site2
  #   networks:
  #     - site2
  #   volumes:
  #     - ./app:/app



  # nginx-2:
  #   image: nginx:alpine
  #   container_name: nginx-2
  #   networks:
  #     - site2
  #   volumes:
  #     - ./app:/app
  #     - ./docker/nginx/site2.conf:/etc/nginx/conf.d/z-overrides.conf

  # nginx-3:
  #   image: nginx:alpine
  #   container_name: nginx-3
  #   networks:
  #     - site2
  #   volumes:
  #     - ./app:/app
  #     - ./docker/nginx/site3.conf:/etc/nginx/conf.d/z-overrides.conf

